# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jakub Pogorzelski's blog
tagline:          'Dev blog'
description:      'Personal blog of Jakub Pogorzelski'
url:              https://jpogorzelski.github.io
baseurl:          /blog/

author:
  name:           'Jakub Pogorzelski'
  url:            https://jpogorzelski.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jpogorzelski/blog
